spring:
  datasource:
    url: jdbc:mysql://localhost:3307/rsSystem?serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false